; LilyGO T-Dongle S3 — Cyber Invaders
[platformio]
default_envs = tdongle

[env:tdongle]
platform = espressif32@6.12.0
framework = arduino
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
monitor_rts = 0
monitor_dtr = 0

lib_deps =
  lovyan03/LovyanGFX@^1.2.0
  fastled/FastLED@3.9.15

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_DONGLES3
  -DCORE_DEBUG_LEVEL=0

build_unflags =
  -std=gnu++11

build_src_flags =
  -std=gnu++17
